=== wcarmon/codegen/src/main/resources/json-schema/field.schema.json
{
  "$id": "https://wcarmon.com/schemas/codegen/field.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "description": "Field, Property, Column, ...",
  "properties": {
    "$schema": {
      "format": "uri",
      "type": "string"
    },
    "canLog": {
      "description": "for PII, set false",
      "type": "boolean"
    },
    "canUpdate": {
      "type": "boolean"
    },
    "documentation": {
      "items": {
        "maxLength": 200,
        "minLength": 0,
        "type": "string"
      },
      "maxItems": 100,
      "minItems": 0,
      "type": "array",
      "uniqueItems": false
    },
    "enumType": {
      "type": "boolean"
    },
    "golang": {
      "$ref": "golang-field.schema.json"
    },
    "jvm": {
      "$ref": "jvm-field.schema.json"
    },
    "name": {
      "$ref": "field-name.schema.json"
    },
    "nullable": {
      "type": "boolean"
    },
    "positionInId": {
      "exclusiveMaximum": 8,
      "minimum": 0,
      "type": "integer"
    },
    "precision": {
      "description": "total # significant digits (both sides of decimal point)",
      "exclusiveMaximum": 1000,
      "minimum": 0,
      "type": "integer"
    },
    "protobuf": {
      "$ref": "protobuf-field.schema.json"
    },
    "rdbms": {
      "$ref": "rdbms-column.schema.json"
    },
    "scale": {
      "description": "# decimal digits",
      "exclusiveMaximum": 1000,
      "minimum": 0,
      "type": "integer"
    },
    "signed": {
      "type": "boolean"
    },
    "type": {
      "maxLength": 64,
      "type": "string"
    },
    "validation": {
      "$ref": "field-validation.schema.json"
    }
  },
  "propertyNames": {
    "pattern": "^[$]?[A-Za-z_][A-Za-z0-9]*$"
  },
  "required": [
    "name",
    "type"
  ],
  "title": "Field",
  "type": "object"
}

=== wcarmon/codegen/samples/fields/deadline.field.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/field.schema.json",
  "golang": {
    "defaultValue": {
      "value": null
    }
  },
  "jvm": {
    "defaultValue": {
      "value": null
    }
  },
  "name": "deadline",
  "nullable": true,
  "rdbms": {
    "defaultValue": {
      "value": null
    }
  },
  "type": "Instant"
}
