=== wcarmon/codegen/src/main/resources/json-schema/request.schema.json
{
  "$id": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "description": "configuration for a single run of the code generator",
  "properties": {
    "$schema": {
      "format": "uri",
      "type": "string"
    },
    "allowOverride": {
      "type": "boolean"
    },
    "caseFormatForOutputFile": {
      "enum": [
        "LOWER_CAMEL",
        "LOWER_HYPHEN",
        "LOWER_UNDERSCORE",
        "UPPER_CAMEL",
        "UPPER_UNDERSCORE"
      ]
    },
    "entityConfigDirs": {
      "items": {
        "type": "string"
      },
      "maxItems": 256,
      "minItems": 1,
      "type": "array",
      "uniqueItems": true
    },
    "extraJVMImports": {
      "description": "fully qualified classes/enums/interfaces to import, no semicolons",
      "items": {
        "pattern": "^([a-zA-Z0-9])[a-zA-Z0-9_.]+([a-zA-Z0-9])(.*)?$",
        "type": "string"
      },
      "maxItems": 96,
      "minItems": 0,
      "type": "array",
      "uniqueItems": true
    },
    "extraProtobufImports": {
      "description": "fully qualified classes/enums/interfaces to import, no semicolons",
      "items": {
        "pattern": "^([a-zA-Z0-9])[a-zA-Z0-9_.]+([a-zA-Z0-9])(.*)?$",
        "type": "string"
      },
      "maxItems": 96,
      "minItems": 0,
      "type": "array",
      "uniqueItems": true
    },
    "jvmContextClass": {
      "maxLength": 64,
      "minLength": 1,
      "type": "string"
    },
    "outputDirectory": {
      "maxLength": 250,
      "minLength": 1,
      "type": "string"
    },
    "outputFilenameTemplate": {
      "description": "contains %s placeholder when outputMode=multiple, just a file name when outputMode=single",
      "maxLength": 64,
      "minLength": 2,
      "type": "string"
    },
    "outputMode": {
      "enum": [
        "multiple",
        "single"
      ]
    },
    "package": {
      "maxLength": 250,
      "minLength": 0,
      "type": "string"
    },
    "templateURI": {
      "format": "uri",
      "maxLength": 250,
      "minLength": 1,
      "type": "string"
    }
  },
  "propertyNames": {
    "pattern": "^[$]?[A-Za-z_][A-Za-z0-9]*$"
  },
  "required": [
    "entityConfigDirs",
    "outputDirectory",
    "outputFilenameTemplate",
    "outputMode",
    "templateURI"
  ],
  "title": "Code generation request",
  "type": "object"
}

=== wcarmon/codegen/samples/config-root/dao.traced-delegate.java8.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.wcarmon.chrono.model00.*",
    "com.wcarmon.ub.model.UBUuid",
    "io.opentracing.Span",
    "io.opentracing.Tracer",
    "java.util.function.Function",
    "java.util.function.Supplier",
    "java.util.List",
    "java.util.Objects",
    "java.util.Set"
  ],
  "jvmContextClass": "com.wcarmon.chrono.context.ChronoContext",
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/dao00",
  "outputFilenameTemplate": "%sTracedDAO.java",
  "outputMode": "multiple",
  "package": "com.wcarmon.chrono.dao00",
  "templateURI": "classpath:/templates/dao/traced-delegate.java8.ftl"
}

=== wcarmon/codegen/samples/config-root/mapper.sqldelight.kotlin.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.fasterxml.jackson.core.type.TypeReference",
    "com.fasterxml.jackson.databind.ObjectMapper",
    "com.fasterxml.jackson.databind.ObjectWriter",
    "com.wcarmon.chrono.dao30.*",
    "com.wcarmon.chrono.model30.*"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/mapper30",
  "outputFilenameTemplate": "SQLDelightMappers.kt",
  "outputMode": "single",
  "package": "com.wcarmon.chrono.mapper30",
  "templateURI": "classpath:/templates/sqldelight/mappers.kotlin.ftl"
}

=== wcarmon/codegen/samples/config-root/sql.queries.java8.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/sql00",
  "outputFilenameTemplate": "SQLQueries.java",
  "outputMode": "single",
  "package": "com.wcarmon.chrono.sql00",
  "templateURI": "classpath:/templates/jdbc-template/sql.queries.java8.ftl"
}

=== wcarmon/codegen/samples/config-root/spring-web.html-controller.java8.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.wcarmon.chrono.dao00.*",
    "com.wcarmon.chrono.model00.*",
    "io.opentracing.Tracer",
    "javax.servlet.http.HttpServletRequest",
    "org.springframework.web.bind.annotation.DeleteMapping",
    "org.springframework.web.bind.annotation.GetMapping",
    "org.springframework.web.bind.annotation.PatchMapping",
    "org.springframework.web.bind.annotation.PathVariable",
    "org.springframework.web.bind.annotation.PostMapping",
    "org.springframework.web.bind.annotation.PutMapping",
    "org.springframework.web.bind.annotation.RequestBody",
    "org.springframework.web.bind.annotation.RequestHeader",
    "org.springframework.web.bind.annotation.RequestMapping",
    "org.springframework.web.bind.annotation.RestController"
  ],
  "jvmContextClass": "com.wcarmon.chrono.context.ChronoContext",
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/web/html00",
  "outputFilenameTemplate": "%sHTMLController.kt",
  "outputMode": "multiple",
  "package": "com.wcarmon.chrono.web.html00",
  "templateURI": "classpath:/templates/spring-web/html-controller.java8.ftl"
}

=== wcarmon/codegen/samples/config-root/sql.create-table.postgres.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/sql/create-tables",
  "outputFilenameTemplate": "postgres.sql",
  "outputMode": "single",
  "package": "",
  "templateURI": "classpath:/templates/sql/create-table.postgres.ftl"
}

=== wcarmon/codegen/samples/config-root/dao.traced-delegate.coroutine.kotlin.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.wcarmon.chrono.dao31.*",
    "com.wcarmon.chrono.model30.*",
    "com.wcarmon.tracing.SpanElement",
    "com.wcarmon.ub.model.UBUuid",
    "io.opentracing.Span",
    "io.opentracing.Tracer",
    "java.util.function.Function",
    "kotlin.coroutines.coroutineContext",
    "kotlinx.coroutines.withContext"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/kotlin/com/wcarmon/chrono/dao31",
  "outputFilenameTemplate": "%sTracedDAO.kt",
  "outputMode": "multiple",
  "package": "com.wcarmon.chrono.dao31",
  "templateURI": "classpath:/templates/dao/traced-delegate.coroutine.kotlin.ftl"
}

=== wcarmon/codegen/samples/config-root/sq.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/main/sqldelight/com/wcarmon/chrono/dao30",
  "outputFilenameTemplate": "%s.sq",
  "outputMode": "multiple",
  "package": "com.wcarmon.chrono.dao30",
  "templateURI": "classpath:/templates/sqldelight/sq.ftl"
}

=== wcarmon/codegen/samples/config-root/proto.entities.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/proto",
  "outputFilenameTemplate": "entities.proto",
  "outputMode": "single",
  "package": "com.wcarmon.chrono.grpc",
  "templateURI": "classpath:/templates/protobuf/entities.ftl"
}
