=== wcarmon/codegen/src/main/resources/json-schema/request.schema.json
{
  "$id": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "description": "configuration for a single run of the code generator",
  "properties": {
    "$schema": {
      "format": "uri",
      "type": "string"
    },
    "allowOverride": {
      "type": "boolean"
    },
    "caseFormatForOutputFile": {
      "enum": [
        "LOWER_CAMEL",
        "LOWER_HYPHEN",
        "LOWER_UNDERSCORE",
        "UPPER_CAMEL",
        "UPPER_UNDERSCORE"
      ]
    },
    "entityConfigDirs": {
      "items": {
        "type": "string"
      },
      "maxItems": 256,
      "minItems": 1,
      "type": "array",
      "uniqueItems": true
    },
    "extraJVMImports": {
      "description": "fully qualified classes/enums/interfaces to import, no semicolons",
      "items": {
        "pattern": "^([a-zA-Z0-9])[a-zA-Z0-9_.]+([a-zA-Z0-9])(.*)?$",
        "type": "string"
      },
      "maxItems": 96,
      "minItems": 0,
      "type": "array",
      "uniqueItems": true
    },
    "extraProtobufImports": {
      "description": "fully qualified classes/enums/interfaces to import, no semicolons",
      "items": {
        "pattern": "^([a-zA-Z0-9])[a-zA-Z0-9_.]+([a-zA-Z0-9])(.*)?$",
        "type": "string"
      },
      "maxItems": 96,
      "minItems": 0,
      "type": "array",
      "uniqueItems": true
    },
    "jvmContextClass": {
      "maxLength": 64,
      "minLength": 1,
      "type": "string"
    },
    "outputDirectory": {
      "maxLength": 250,
      "minLength": 1,
      "type": "string"
    },
    "outputFilenameTemplate": {
      "description": "contains %s placeholder when outputMode=multiple, just a file name when outputMode=single",
      "maxLength": 64,
      "minLength": 2,
      "type": "string"
    },
    "outputMode": {
      "enum": [
        "multiple",
        "single"
      ]
    },
    "package": {
      "maxLength": 250,
      "minLength": 0,
      "type": "string"
    },
    "templateURI": {
      "format": "uri",
      "maxLength": 250,
      "minLength": 1,
      "type": "string"
    }
  },
  "propertyNames": {
    "pattern": "^[$]?[A-Za-z_][A-Za-z0-9]*$"
  },
  "required": [
    "entityConfigDirs",
    "outputDirectory",
    "outputFilenameTemplate",
    "outputMode",
    "templateURI"
  ],
  "title": "Code generation request",
  "type": "object"
}

=== wcarmon/codegen/samples/config-root/spring.config.traced-dao.kotlin.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.wcarmon.chrono.dao30.*",
    "io.opentracing.Tracer",
    "java.util.function.Function",
    "org.springframework.context.annotation.Bean",
    "org.springframework.context.annotation.Configuration"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/kotlin/com/wcarmon/chrono/config30",
  "outputFilenameTemplate": "TracedDAOBeans.kt",
  "outputMode": "single",
  "package": "com.wcarmon.chrono.config30",
  "templateURI": "classpath:/templates/spring/configuration.traced-dao.kotlin.ftl"
}

=== wcarmon/codegen/samples/config-root/proto.mapper.core.java8.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.wcarmon.chrono.grpc.*",
    "com.wcarmon.chrono.model00.*",
    "java.util.Collection",
    "java.util.Collections",
    "java.util.List",
    "java.util.Objects",
    "java.util.Set",
    "java.util.stream.Collectors"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/proto00",
  "outputFilenameTemplate": "ProtoMappers.java",
  "outputMode": "single",
  "package": "com.wcarmon.chrono.proto00",
  "templateURI": "classpath:/templates/proto/proto-mapper.java8.ftl"
}

=== wcarmon/codegen/samples/config-root/sql.drop-table.sqlite.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/sql/drop-tables",
  "outputFilenameTemplate": "sqlite.sql",
  "outputMode": "single",
  "package": "",
  "templateURI": "classpath:/templates/sql/drop-table.sqlite.ftl"
}

=== wcarmon/codegen/samples/config-root/dao.jdbc-template.java8.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.fasterxml.jackson.databind.ObjectWriter",
    "com.wcarmon.chrono.dao00.*",
    "com.wcarmon.chrono.model00.*",
    "com.wcarmon.chrono.sql00.SQLQueries",
    "java.sql.Types",
    "java.util.Collection",
    "java.util.Collections",
    "java.util.List",
    "java.util.Map",
    "java.util.Objects",
    "java.util.Set",
    "org.springframework.jdbc.core.JdbcTemplate",
    "org.springframework.jdbc.core.RowMapper"
  ],
  "jvmContextClass": "com.wcarmon.chrono.context.ChronoContext",
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/dao00",
  "outputFilenameTemplate": "%sDAOImpl.java",
  "outputMode": "multiple",
  "package": "com.wcarmon.chrono.dao00",
  "templateURI": "classpath:/templates/jdbc-template/dao-impl.java8.ftl"
}

=== wcarmon/codegen/samples/config-root/data-class.kotlin.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.fasterxml.jackson.annotation.JsonPropertyOrder",
    "com.fasterxml.jackson.databind.annotation.JsonDeserialize",
    "com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/model30",
  "outputFilenameTemplate": "%s.kt",
  "outputMode": "multiple",
  "package": "com.wcarmon.chrono.model30",
  "templateURI": "classpath:/templates/pojo/data-class.kotlin.ftl"
}

=== wcarmon/codegen/samples/config-root/dao.interface.java8.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.wcarmon.chrono.model01.*",
    "java.util.Collection",
    "java.util.List",
    "java.util.Map",
    "java.util.Set"
  ],
  "jvmContextClass": "com.wcarmon.chrono.context.ChronoContext",
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/dao01",
  "outputFilenameTemplate": "%sDAO.java",
  "outputMode": "multiple",
  "package": "com.wcarmon.chrono.dao01",
  "templateURI": "classpath:/templates/dao/interface.java8.ftl"
}

=== wcarmon/codegen/samples/config-root/type-references.kotlin.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.fasterxml.jackson.core.type.TypeReference",
    "com.fasterxml.jackson.databind.ObjectMapper"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/model30",
  "outputFilenameTemplate": "TypeReferences.kt",
  "outputMode": "single",
  "package": "com.wcarmon.chrono.model30",
  "templateURI": "classpath:/templates/pojo/type-references.kotlin.ftl"
}

=== wcarmon/codegen/samples/config-root/spring.config.row-mapper.kotlin.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.fasterxml.jackson.databind.ObjectMapper",
    "com.wcarmon.chrono.model30.*",
    "com.wcarmon.chrono.rowmappers30.*",
    "org.springframework.context.annotation.Bean",
    "org.springframework.context.annotation.Configuration",
    "org.springframework.jdbc.core.RowMapper"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/kotlin/com/wcarmon/chrono/config30",
  "outputFilenameTemplate": "RowMapperBeans.kt",
  "outputMode": "single",
  "package": "com.wcarmon.chrono.config30",
  "templateURI": "classpath:/templates/spring/configuration.row-mapper.kotlin.ftl"
}
