=== wcarmon/codegen/src/main/resources/json-schema/request.schema.json
{
  "$id": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "description": "configuration for a single run of the code generator",
  "properties": {
    "$schema": {
      "format": "uri",
      "type": "string"
    },
    "allowOverride": {
      "type": "boolean"
    },
    "caseFormatForOutputFile": {
      "enum": [
        "LOWER_CAMEL",
        "LOWER_HYPHEN",
        "LOWER_UNDERSCORE",
        "UPPER_CAMEL",
        "UPPER_UNDERSCORE"
      ]
    },
    "entityConfigDirs": {
      "items": {
        "type": "string"
      },
      "maxItems": 256,
      "minItems": 1,
      "type": "array",
      "uniqueItems": true
    },
    "extraJVMImports": {
      "description": "fully qualified classes/enums/interfaces to import, no semicolons",
      "items": {
        "pattern": "^([a-zA-Z0-9])[a-zA-Z0-9_.]+([a-zA-Z0-9])(.*)?$",
        "type": "string"
      },
      "maxItems": 96,
      "minItems": 0,
      "type": "array",
      "uniqueItems": true
    },
    "extraProtobufImports": {
      "description": "fully qualified classes/enums/interfaces to import, no semicolons",
      "items": {
        "pattern": "^([a-zA-Z0-9])[a-zA-Z0-9_.]+([a-zA-Z0-9])(.*)?$",
        "type": "string"
      },
      "maxItems": 96,
      "minItems": 0,
      "type": "array",
      "uniqueItems": true
    },
    "jvmContextClass": {
      "maxLength": 64,
      "minLength": 1,
      "type": "string"
    },
    "outputDirectory": {
      "maxLength": 250,
      "minLength": 1,
      "type": "string"
    },
    "outputFilenameTemplate": {
      "description": "contains %s placeholder when outputMode=multiple, just a file name when outputMode=single",
      "maxLength": 64,
      "minLength": 2,
      "type": "string"
    },
    "outputMode": {
      "enum": [
        "multiple",
        "single"
      ]
    },
    "package": {
      "maxLength": 250,
      "minLength": 0,
      "type": "string"
    },
    "templateURI": {
      "format": "uri",
      "maxLength": 250,
      "minLength": 1,
      "type": "string"
    }
  },
  "propertyNames": {
    "pattern": "^[$]?[A-Za-z_][A-Za-z0-9]*$"
  },
  "required": [
    "entityConfigDirs",
    "outputDirectory",
    "outputFilenameTemplate",
    "outputMode",
    "templateURI"
  ],
  "title": "Code generation request",
  "type": "object"
}

=== wcarmon/codegen/samples/config-root/type-references.java8.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.fasterxml.jackson.core.type.TypeReference",
    "java.util.List",
    "java.util.Set"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/model01",
  "outputFilenameTemplate": "TypeReferences.java",
  "outputMode": "single",
  "package": "com.wcarmon.chrono.model01",
  "templateURI": "classpath:/templates/pojo/type-references.java8.ftl"
}

=== wcarmon/codegen/samples/config-root/dao.interface.coroutine.kotlin.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.wcarmon.chrono.model30.*",
    "com.wcarmon.ub.model.UBUuid"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/kotlin/com/wcarmon/chrono/dao31",
  "outputFilenameTemplate": "%sDAO.kt",
  "outputMode": "multiple",
  "package": "com.wcarmon.chrono.dao31",
  "templateURI": "classpath:/templates/dao/interface.coroutine.kotlin.ftl"
}

=== wcarmon/codegen/samples/config-root/proto.mapper.core.kotlin.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.wcarmon.chrono.grpc.*",
    "com.wcarmon.chrono.model30.*",
    "com.wcarmon.ub.model.UBUuid"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/kotlin/com/wcarmon/chrono/protobuf30",
  "outputFilenameTemplate": "ProtobufMappers.kt",
  "outputMode": "single",
  "package": "com.wcarmon.chrono.protobuf30",
  "templateURI": "classpath:/templates/protobuf/proto-mapper.kotlin.ftl"
}

=== wcarmon/codegen/samples/config-root/fake-entity.kotlin.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.fasterxml.jackson.databind.ObjectWriter",
    "com.github.javafaker.Faker",
    "com.wcarmon.chrono.model30.*",
    "com.wcarmon.ub.model.UBUuid",
    "java.net.URI",
    "java.net.URL",
    "java.time.Clock",
    "java.time.Duration",
    "java.time.Period",
    "java.util.concurrent.ThreadLocalRandom",
    "java.util.concurrent.TimeUnit",
    "java.util.UUID"
  ],
  "jvmContextClass": "com.wcarmon.chrono.context.ChronoContext",
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/genTest/kotlin/com/wcarmon/chrono/fake30",
  "outputFilenameTemplate": "FakeEntityBuilders.kt",
  "outputMode": "single",
  "package": "com.wcarmon.chrono.fake30",
  "templateURI": "classpath:/templates/test/fake-entity.kotlin.ftl"
}

=== wcarmon/codegen/samples/config-root/dao.traced-delegate.kotlin.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.wcarmon.chrono.dao30.*",
    "com.wcarmon.chrono.model30.*",
    "com.wcarmon.chrono.sql30.*",
    "io.opentracing.Span",
    "io.opentracing.Tracer",
    "java.util.function.Function"
  ],
  "jvmContextClass": "com.wcarmon.chrono.context.ChronoContext",
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/dao30",
  "outputFilenameTemplate": "%sTracedDAO.kt",
  "outputMode": "multiple",
  "package": "com.wcarmon.chrono.dao30",
  "templateURI": "classpath:/templates/dao/traced-delegate.kotlin.ftl"
}

=== wcarmon/codegen/samples/config-root/spring.config.dao-impl.kotlin.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.fasterxml.jackson.databind.ObjectWriter",
    "com.wcarmon.chrono.dao30.*",
    "com.wcarmon.chrono.model30.*",
    "java.time.Clock",
    "org.springframework.context.annotation.Bean",
    "org.springframework.context.annotation.Configuration",
    "org.springframework.jdbc.core.JdbcTemplate",
    "org.springframework.jdbc.core.RowMapper"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/kotlin/com/wcarmon/chrono/config30",
  "outputFilenameTemplate": "DAOImplBeans.kt",
  "outputMode": "single",
  "package": "com.wcarmon.chrono.config30",
  "templateURI": "classpath:/templates/spring/configuration.dao-impl.kotlin.ftl"
}

=== wcarmon/codegen/samples/config-root/dao.interface.kotlin.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "extraJVMImports": [
    "com.wcarmon.chrono.model30.*"
  ],
  "jvmContextClass": "com.wcarmon.chrono.context.ChronoContext",
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/dao30",
  "outputFilenameTemplate": "%sDAO.kt",
  "outputMode": "multiple",
  "package": "com.wcarmon.chrono.dao30",
  "templateURI": "classpath:/templates/dao/interface.kotlin.ftl"
}

=== wcarmon/codegen/samples/config-root/sql.create-table.sqlite.request.json
{
  "$schema": "https://wcarmon.com/schemas/codegen/request.schema.json",
  "allowOverride": true,
  "entityConfigDirs": [
    "file:///home/wcarmon/git-repos/codegen/samples/entities"
  ],
  "outputDirectory": "file:///home/wcarmon/git-repos/modern-jvm/sandbox/src/gen/java/com/wcarmon/chrono/create-tables",
  "outputFilenameTemplate": "sqlite.sql",
  "outputMode": "single",
  "package": "",
  "templateURI": "classpath:/templates/sql/create-table.sqlite.ftl"
}
